name: Lint
on: [push, pull_request]

jobs:
  # golangci:
  #   name: golangci-lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: latest
  #         args: "--config .golintci.yml"
  #         only-new-issues: true # only show new issues in the PR, not all.

  tfproviderlint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: make terraform-provider-lint
